const CHAR_CODE_LOWERCASE_MIN = 97;
const CHAR_CODE_LOWERCASE_MAX = 122;
const CHAR_CODE_UPPERCASE_MIN = 65;
const CHAR_CODE_UPPERCASE_MAX = 90;
const ENGLISH_ALPHABET = 26;

module.exports = {
  CHAR_CODE_LOWERCASE_MIN,
  CHAR_CODE_LOWERCASE_MAX,
  CHAR_CODE_UPPERCASE_MIN,
  CHAR_CODE_UPPERCASE_MAX,
  ENGLISH_ALPHABET,
};
